#!/usr/bin/env ruby
new_migrations = `svn st`.split("\n").collect {|f| f =~ /\?\s+db\/migrate\/(\d{3}_\w+\.rb)/ ? $1 : nil}.compact
last_commited_migration = `ls db/migrate`.split("\n").collect do |file|
  new_migrations.include?(file) ? nil :
    file =~ /(\d{3})_\w+\.rb/ ? $1.to_i : nil
end.compact.max

new_migrations.each_with_index do |migration, i|
  new_name = "%03d_%s" % [last_commited_migration + 1 + i, migration[/\d{3}_(\w+\.rb)/, 1]]
  `mv db/migrate/#{migration} db/migrate/#{new_name}`
end

`rake db:rebuild`