#!/usr/bin/env ruby
require File.dirname(__FILE__) + "/_printlog/printlog"

options = ARGV.inject({}) do |hash, option|
  key, value = option.split("=").collect {|thing| thing.lstrip.rstrip}
  hash[key.to_sym] = value
  hash
end

printer = Printlog.new(`pwd`, options)
puts printer.report
