#!/usr/bin/env ruby
require File.dirname(__FILE__) + "/_printlog/printlog"
require "tempfile"

options = ARGV.inject({}) do |hash, option|
  key, value = option.split("=").collect {|thing| thing.lstrip.rstrip}
  hash[key.to_sym] = value
  hash
end

stdout = options.delete(:stdout)
report = options[:convert].nil? ?
  Printlog.new(`pwd`, options).report :
  Printlog::Converter.new(File.read(options[:convert])).report(options[:format])
stdout ? puts(report) : `echo "#{report}" | mate -a`